version: '3.2'

networks:
  phalcon-network:
    driver: bridge
services:

  # postgres DB
  phalcon-db:
    image: postgres:14.2-alpine
    container_name: my-ticket-postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    networks:
      - phalcon-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: myticket
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c log_statement=all

  # WEB
  phalcon-web:
    build:
      context: .
      args:
        - env=driver
        - phalcon_version=v3.4.3
    container_name: my-ticket-web
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./web
        target: /var/www
    networks:
      - phalcon-network
    working_dir: /var/www/html
    depends_on:
      - phalcon-db
    links:
      - "phalcon-redis:redis"

  # redis cache
  phalcon-redis:
    image: redis:7-alpine
    container_name: my-ticket-redis
    networks:
      - phalcon-network
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: redis-server --appendonly yes --requirepass Azerty
    volumes:
      - ./redis_data:/data
